# prefix key
set -g prefix C-a

# reload configuration
bind r source-file ~/.config/tmux/tmux.conf

# move pane
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -n S-left select-pane -L
bind -n S-down select-pane -D
bind -n S-up select-pane -U
bind -n S-right select-pane -R

# resize pane
bind -r C-h resize-pane -L 10
bind -r C-l resize-pane -R 10
bind -r C-j resize-pane -D 10
bind -r C-k resize-pane -U 10

# enable mouse
set-option -g mouse on

# bind - split-window -v
# bind \ split-window -h

# set -g set-clipboard on

# bind-key C-v paste-buffer
